- src/partials/footer.html
- src/sass/footer/_footer-desctop.scss
- src/sass/footer/_footer-global.scss
- src/sass/footer/_footer-mobile.scss
- src/sass/footer/_footer-tablet.scss
> Footer disign added

- src/index.html
- src/partials/products.html
- src/sass/products/products-global.scss
Я перебрал немного код, теперь билд через npm происходит без ошибок и все работает
> build bug fixed

- src/sass/advantages/_advantages-desctop.scss
> правки decktop

- src/partials/products.html
Перезалив products.html (як було)
> products.html upd

- package-lock.json
- src/partials/products.html
- src/sass/products/products-desctop.scss
- src/sass/products/products-global.scss
- src/sass/products/products-mobile.scss
- src/sass/products/products-tablet.scss
> products upd (14:43)

- src/index.js
- src/partials/gallery.html
- src/sass/customer-reviews/_customer-reviews-global.scss
- src/sass/gallery/_gallery-global.scss
Добавил второй слайдер для галереи
> Customer review3

- src/sass/customer-reviews/_customer-reviews-global.scss
- src/sass/gallery/_gallery-global.scss
> Почистил css для слайдеров

- src/sass/gallery/_gallery-global.scss
> bg added to gallery

- src/partials/advantages.html
- src/sass/advantages/_advantages-desctop.scss
- src/sass/advantages/_advantages-tablet.scss
> advant-svg-cow

- src/partials/customer-reviews.html
- src/partials/gallery.html
- src/sass/gallery/_gallery-global.scss
сделал srcset для галери и кастомерс ревью,  подогнал размеры для мобилки и таблета
> сделал srcset для галери и кастомерс ревью

- src/partials/advantages.html
пофікшено баг з іконками корів
> advantages cow-ico fixed

- package-lock.json
- src/index.html
- src/index.js
- src/partials/MODAL.html
- src/partials/products.html
- src/sass/index.scss
- src/sass/modal.scss
Застосовано принцип з https://codepen.io/dan_postnov/pen/gjBqPb (у файлі index.js). У MODAL.html вставлено діви модалок 1, 3 і 4. Інші пусті. Знизу тестові посилання на запуск кожної модалки. З кнопки запускається тільки модалка №3 (стрілочки у секції продуктів). Стилі необхідно допрацювати
> Modals-0.1

- src/partials/about.html
- src/sass/about/_about-global.scss
я сделал кнопку многострадальную в секции about
> button fixed

- src/index.html
- src/partials/gallery.html
пофиксил ошибку валидатора (кроме дублирующихся айди чтобы не поламать скрипты)
> Validator fix

- src/partials/contacts.html
- src/sass/_global.scss
> Contacts button fixed

- src/sass/about/_about-global.scss
- src/sass/advantages/_advantages-desctop.scss
- src/sass/advantages/_advantages-global.scss
- src/sass/advantages/_advantages-mobile.scss
- src/sass/advantages/_advantages-tablet.scss
- src/sass/contacts/_contacts-desctop.scss
- src/sass/contacts/_contacts-global.scss
- src/sass/contacts/_contacts-mobile.scss
- src/sass/contacts/_contacts-tablet.scss
- src/sass/hero-header/_hero-header-desctop.scss
- src/sass/hero-header/_hero-header-mobile.scss
- src/sass/hero-header/_hero-header-tablet.scss
- src/sass/products/products-global.scss
пофіксив всі розміри контейнерів
> Container fix

- src/partials/modal/ingredients-modal.html
- src/sass/index.scss
- src/sass/modal/_ingredients.scss
Перероблено файли модалки, аби вона хоч відображалась і працювали кнопки
!!! У _ingredients.scss присутній клас .modal, що впливає на інші модалки
> ingredients

- src/sass/about/_about-global.scss
Видалила непотрібні паддінги в своїй секції
> removed unnesessary paddings

- src/partials/modal/ingredients-modal.html
- src/sass/modal/_ingredients.scss
Я поправил картинку в ингредиентах и теперь она по центру, а не слева как была
> ingredients modal img fix

- src/sass/products/products-global.scss
> product-fix
